apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rep
  namespace: nginx
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-rep-pod
          image: nginx:1.14.2
          ports:
            - containerPort: 80
