apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-bind
  namespace: apache

subjects:
  - kind: User
    name: Vibhuti
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: role-define
  apiGroup: rbac.authorization.k8s.io
