apiVersion: v1
kind: Pod
metadata:
  name: init-test
  namespace: init

spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh", "-c", "echo 'Intialization started'; sleep 10s; echo 'Intialization completed'"]

  containers:
  - name: main-container
    image: busybox:latest
    command: ["sh", "-c" , "echo 'Intialization main container started'"]
